### ISSUE TITLE
App Crashes when tap to the screen

### ISSUE THREAD

**Issue by dariocavada** [Aish05/ARCoreFurnitureTryout#1]
I've tried to compile the app, but I've the following error after tap the screen to choose the furniture:

```
2020-06-17 17:28:11.864 9111-9111/com.aish.arseup D/AndroidRuntime: Shutting down VM
2020-06-17 17:28:11.867 9111-9111/com.aish.arseup E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.aish.arseup, PID: 9111
    kotlin.UninitializedPropertyAccessException: lateinit property selectedFurniture has not been initialized
        at com.aish.arseup.MainActivity.loadModel(MainActivity.kt:159)
        at com.aish.arseup.MainActivity.access$loadModel(MainActivity.kt:29)
        at com.aish.arseup.MainActivity$setupDopubleTapARPlaneListener$1.onTapPlane(MainActivity.kt:60)
```

**Comment by Aish05** [comment]
I ll look into it
